### ISSUE TITLE
torque_read_out_of_range

### ISSUE THREAD

**Issue by AndPatr** [ADVRHumanoids/awesome_leg#12]
@ntsagarakis, @ADVRHumanoids/advr-facility 
I was testing a small jump on the leg (using a xbto2 rt plugin). My plugin automatically replays the trajectory after a predefined period of time.
I observed the following:
- The first time, the jump is performed without errors on both terminals where I was running xbot2 and the ecat_master
- The second time the jump is replayed, after impacting the ground, the leg shuts down and I get a "m3_torque3_read_out_of_range" error on the ecat console. The xbot2 terminal does not show any position or velocity bound violation errors.
The following graphs show the issue.
Hip torque
![effort_hip](https://user-images.githubusercontent.com/90312267/182612550-a7d5a522-2ba7-4948-9e3e-e523da14e651.png)
Knee torque:
![effort_knee](https://user-images.githubusercontent.com/90312267/182612505-c8aec9f7-5867-4955-899e-923a290dfe4b.png)
Hip pos. VS reference:
![link_pos_hip](https://user-images.githubusercontent.com/90312267/182614549-6f734b63-7dc2-462a-8d4c-65361d1d65c0.png)
Knee pos. VS reference:
![link_pos_knee](https://user-images.githubusercontent.com/90312267/182614708-fbca721f-e29b-4ea7-b26b-98f0ba96ab77.png)

I will further investigate the problem by performing more tests, but it might be necessary to flash larger torque limits in the firmware to allow jump tests.

**Comment by TheCzar87** [comment]
Hi @AndPatr 
First of all I would like to thank you for the experiment report: brief, professional and accurate. 
@liesrock @alaurenzi @ntsagarakis please broadcast it to all the researchers, as a reference of how the issues should be opened and reported.

Back to the unexpected behaviour: 
**_Did the leg shut off because power supply failed?
The leg was controlled in impedance mode or in position mode?_** 

the error **_"m3_torque3_read_out_of_range"_** shutdown the joint only if you are controlling the leg in impedance mode, in all the other modes is handled as a warning for the ethercat master. 

Although looks like that this is a real warning because the torque of the second joint (knee pitch) was above the 150Nm. Right now I cannot recall exactly but I guess that the gear ratio is 50:1 (even if is 80:1 the max peak torque is 178.56Nm), therefore the maximum torque set in the firmware is 111.60Nm.

My guess is that the power suplly shutdown due an high current demand requested after the impact, and this generated the misbehaviour. We can raise the MaxTorque parameter but then we will risk the permanent damage of the harmonic drive (to me we can risk it, so at least we know exactly how far, in terms of torque, we can go with this gear ratio.

Something that can help for sure, is investigate and solve once for all the high friction all those joints have. 
For this is better to involve Lorenzo in it.

@ntsagarakis what do you think about it?

**Comment by ntsagarakis** [comment]
The momentary peak torque of the harmonic with the 50:1 ratio is 186Nm so we can increase the limit to this level. 
So we can check the torque peak limit in the firmware that triggers the shutting down of the joint controller and update it to this value.

Furthermore, as this is clearly a torque spike occurring during the landing impact I guess we can do the following two things to reduce the impact peak torque.  

i) Modify the leg posture at the impact time to reduce the impact force lever arm with respect to the knee (basically land with a less bend knee). I see that we are about 2 rad at the time we have the impact torque.

ii) Reduce the stiffness of the foot to increase impact time and filter the impact force.

For the shutdown we need also to verify that this is not caused by some current saturation of the power supply. What was the current limit set during the experiments?

**Comment by TheCzar87** [comment]
Hi Nikos,

I had the same tought on the power supply (the max phase current now is 63A) but I think that the Andrea is referencing the "shutdown" as joint uncontrolled, caused by the fault "m3_torque3_read_out_of_range" in Impedance mode.
For be sure of it, we need the reply of @AndPatr 
About the parameter increase, I will do it today. 
I will be available until the 10th of August, after that I will be on leave until the 5th of september.

**Comment by AndPatr** [comment]
@TheCzar87 thanks for the prompt response.
Yes, I forgot to mention that I was controlling the leg in impedance mode with stiffness and damping coefficients set to, respectively, to 1000 and 15. Also yes, by shutdown I mean that joints are left uncontrolled and the leg simply folds on itself. The power supply always remained operational. During the test I didn't notice anything strange; only the leg going down.
By the way, if you look at the graphs, the limit of approximately 112 Nm is already exceed during the first jump (the knee actuator goes below -150 Nm, while the hip is ok), but the leg does not shutdown. During the second jump, the hip actuator goes beyond the limit too and the leg shuts down. I do not understand why the shutdown seems to happen only when the hip torque limits are exceeded, but this does not happen for the knee. 
Furthermore, for sure the high friction on the  joints does not help.
Also, the terminal shows the error only on "m3", which I guess is the hip motor.
@ntsagarakis probably point ii) will not be of great help. The rubber sheet we put beneath the leg is already quite soft.
For the current limits, the only information I can provide you with is that the trajectories are generated imposing limits on estimated joint currents (using the calibrated model we developed some time ago). But I don't know which current limits were set in the firmware (if any) during the experiments. 
Also, I will repeat the experiment this morning and also log joint currents, since I was not logging them yesterday.

**Comment by ntsagarakis** [comment]
Ok can you also report the current limit setting on the power supply?

To me form what you describe is not clear if the cut is due going overt the torque limit set in the joints. The fact that you already went overt the limit in the first jump but the leg did not cut suggests to check also some other effects that are happening during the impact time. For example in that instance the motors are braking that may result to voltage spikes in the power bus if the energy recuperation circuit is not enough to keep the voltage peaks under a certain limit. This may result to the shutting down of the motor driver.  

------------------------------------------------------------------------------
By the way, if you look at the graphs, the limit of approximately 112 Nm is already exceed during the first jump (the knee actuator goes below -150 Nm, while the hip is ok), but the leg does not shutdown. During the second jump, the hip actuator goes beyond the limit too and the leg shuts down. I do not understand why the shutdown seems to happen only when the hip torque limits are exceeded, but this does not happen for the knee
------------------------------------------------------------------------------

The fact the the driver does not shutdown in the first jump may be also because of the check done on the torque, which should be maintained for at least a number of samples   above the peak torque limit set.  So the different behavior you describe above can be because of this. 
We can increase the number of samples to make the check less sensitive to instantaneous peaks.

Anyway we need to verify :

i) Peak torque limit and set it to 186Nm,  possibly also increasing the number of continues samples that the torque should be maintained above the limit for triggering the shutting down of the controller.

ii) Verify the current limit of the power supply, setting it above 30A.

iii) Check that the energy dissipation circuit is working properly and verify with an oscilloscope that there are no voltage spikes in the power bus during landing.

**Comment by TheCzar87** [comment]
Hi Nikos,
Please see below.

> Ok can you also report the current limit setting on the power supply?
> 
**Is set to 100A, more than enough I would say :-)**

> To me form what you describe is not clear if the cut is due going overt the torque limit set in the joints. The fact that you already went overt the limit in the first jump but the leg did not cut suggests to check also some other effects that are happening during the impact time. For example in that instance the motors are braking that may result to voltage spikes in the power bus if the energy recuperation circuit is not enough to keep the voltage peaks under a certain limit. This may result to the shutting down of the motor driver.

**This does not happen, otherwise the m3_hardware_error and other faults will pop up. I'm quite confidente that the motor driver shutdown due torque out of range, during Impedance mode.**

> ## By the way, if you look at the graphs, the limit of approximately 112 Nm is already exceed during the first jump (the knee actuator goes below -150 Nm, while the hip is ok), but the leg does not shutdown. During the second jump, the hip actuator goes beyond the limit too and the leg shuts down. I do not understand why the shutdown seems to happen only when the hip torque limits are exceeded, but this does not happen for the knee
> 
> The fact the the driver does not shutdown in the first jump may be also because of the check done on the torque, which should be maintained for at least a number of samples above the peak torque limit set. So the different behavior you describe above can be because of this. We can increase the number of samples to make the check less sensitive to instantaneous peaks.

The check is not working on the peaks, is filtered to 10 points (10ms). We can increase the filter but we need to flash and introduce a new firmware. In my opinion is working ok: the parameter inside the FW was set
 to 111Nm and the fault has been triggered above the 150Nm.

> 
> Anyway we need to verify :
> 
> i) Peak torque limit and set it to 186Nm, possibly also increasing the number of continues samples that the torque should be maintained above the limit for triggering the shutting down of the controller.
**_DONE_**
> 
> ii) Verify the current limit of the power supply, setting it above 30A.
**_Already set to 100A_**
> 
> iii) Check that the energy dissipation circuit is working properly and verify with an oscilloscope that there are no voltage spikes in the power bus during landing.
**_To be checked_**
> 
> For the rubber pad on the floor, even if it is soft, only one layer may saturate very fast its maximum deflection resulting in a stiff contact immediately. A thicker pad with the same stiffness may help.

**Comment by ntsagarakis** [comment]
Then no current limit issue if this is set to 100A. But though is this a 5KW power supply to be able to provide 100A at 48V?

----------------------------------------------
The check is not working on the peaks, is filtered to 10 points (10ms). We can increase the filter but we need to flash and introduce a new firmware. In my opinion is working ok: the parameter inside the FW was set
to 111Nm and the fault has been triggered above the 150Nm.
-----------------------------------------------

By peak I mean the peak limit we set in the firmware. Then the check is done comparing the average of a number of  samples  against this peak limit we set.  I am not sure if the 10 points corresponds to 10msec. The torque sampling is done at the rate of 4KHz as the rate of the torque loop. This 10 samples may end-up to be only 2.5msec that is sensitive to give triggers within the impact time.

**Comment by AndPatr** [comment]
@ntsagarakis, @ADVRHumanoids/advr-facility we are still experiencing the torque_reading_out_of_range issue upon touchdown.
This prevents us from performing continuous jumps on the leg.
As a temporary solution we successfully tried with @Lurentz to install some damping sheets beneath the leg. However, as of now, we still have to fix them properly so that they don't slip during the test, etc.. . This is also not the best solution in light of the upcoming demo, since ideally we would want to show the jumps on the bare floor. Putting a damping sheet beneath the leg is great in terms of hardware protection, but not so much for stressing the leg in realistic conditions and for showing its sturdiness.

**Comment by stecorda** [comment]
To avoid the trigger of the fault it is possible to increase the actual limit set in the flash to an higher value.
From the other side if you run in impedance mode is important that the torque reading stays in the voltage reading range otherwise the torque loop is closed on saturated fake torque reading. To be consistent, a full analysis of torque sensor reading has to be performed to understand if the torque you're generating with the impacts can be read from the sensor or causes a saruration or, worse, a mechanical deformation in the torque sensor. We can have a look on this on monday.

**Comment by ntsagarakis** [comment]
In the graphs I see peaks of 150Nm, this is still low for saturating the torque sensor. The sensor is the same as the one in the big joints of Centauro and its saturation is above 250Nm.  We set 111Nm limit in the torque that is related to the expected peak torque of the new leg joint given the 50:1 gear ratio, the 3Nm peak torque of the motor and efficiency of 70-75%. So this limit is related to the actuator limit. Saturation of the torque sensor will appear in much higher torques. 

Given that we are talking about impact torques I will consider raising this limit or increase the number of consecutive samples with torque higher than the limit (I think we have 10 samples now so 10msec above the limit triggers the fault).  First in stead of setting the limit based on the motor limit torque we can consider a limit torque below the momentary peak limit of the harmonic drive that is 186Nm.  We can set the limit at 150Nm. Then we can also increase the number of samples with torque higher than the limit to reach a time interval that is longer than the impact time.  Can we extract from the torque graphs for how long the impact torque is above 150Nm? Then we set the number of samples to cover this time adequately, e.g. we double this time and we find the number of samples we need for this.

**Comment by ntsagarakis** [comment]
> As a temporary solution we successfully tried with @Lurentz to install some damping sheets beneath the leg. However, as of now, we still have to fix them properly so that they don't slip during the test, etc.. . This is also not the best solution in light of the upcoming demo, since ideally we would want to show the jumps on the bare floor. Putting a damping sheet beneath the leg is great in terms of hardware protection, but not so much for stressing the leg in realistic conditions and for showing its sturdiness.

We can also try to print and evauate a softer foot end for the leg.  I will talk to Lorenzo.

**Comment by stecorda** [comment]
Without touching nothing in the actual fw [21071909] max_torque is already set to 186Nm and the max current is 30A.
I've changed the fw to version [221107xx] to increase the number of samples from 10 to 100 that @2KHz means 50msec
impact duration to trigger the torque_read_out_of_range. In any case if the harmonic limit is 186Nm we're already going over the max torque that the harmonic can sustain then maybe is better to understand if use a bigger reduction instead of 50:1.
In any case let's do some tests with this new fw version and let me know.
I've updated the fw on both hip [id 11] and knee [id 12] joints.

**Comment by ntsagarakis** [comment]
if it is already 186Nm why trigger is happening, in the graphs I  see above the peaks are below 186Nm.  In any case we can just extend the samples are you did and see how this will work.  if we need we ca increase the number of samples further e.g. to 200.
We do not want to increase the harmonic, we need to survive playing with the limit. This is an extreme task that will not be performed often. Normally the robot will walk or trot demanding much less torque.  Also the absolute limit of the harmonic is the ratcheting that is usually 8-10 times the continues torque e.g. in this case in the range of 450Nm.  of course going above the peak torque of 186Nm reduces the life of the component.

**Comment by AndPatr** [comment]
@ntsagarakis I will test the leg this afternoon to see if I still detect the torque_reading_out_of_range and let you know.
Thanks @stecorda

**Comment by AndPatr** [comment]
@stecorda, @ntsagarakis before lunch we were started our jump test but, after the first jump, the leg got more or less stuck in the soft sheet beneath the sliding guide and then stopped its jumping sequence without any hints on how this happened in the ecat_master terminal nor in the terminal of the control plugin.
You can see the video [here](https://istitutoitalianotecnologia-my.sharepoint.com/:v:/g/personal/andrea_patrizi_iit_it/ERscDBX--aJAoxvEFtqurNcB57aq8UccTKnEYhXpSbveKw?e=xDfyjR)
Basically, the leg shutdown because the temperature went beyond the threshold:
![Figure_6](https://user-images.githubusercontent.com/90312267/200335272-40f5f191-437c-40bd-83de-b6938302331f.png)
The fan was operating fine on both the hip and the knee but we noticed something strange in the torque/current readings of the knee. 

![Figure_1](https://user-images.githubusercontent.com/90312267/200345492-f6793053-7f2e-4203-a396-1f1b8a54ef8f.png)

As you see, after the jump the leg got stuck in the sheet. What is peculiar is that the knee current saturates to the currently set limit (55 A) but the torques are more or less the same on both axes:
![Figure_5](https://user-images.githubusercontent.com/90312267/200345931-0fbfc717-9a56-41b6-bf7a-1c9bd288ce0b.png)

To check this issue, we made a small test by pushing the joint by hand and then reading the resulting torques and quadrature currents.
- hip:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90312267/200344113-10076efe-77db-4475-8114-ee8a48c5c3e9.png)

- knee:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/90312267/200344316-044fe4ec-61eb-4dec-9279-099b6adad942.png)

As you see the ratio torque/i_q is considerably lower in the knee. We strongly suspect that for some reason the calibration of the phase angle of the knee went off.

**Comment by AndPatr** [comment]
Given the current conditions of the sheet, I will remove it for now

**Comment by ntsagarakis** [comment]
The first thing that it is not clear to  me is what is the condition/pose that makes the knee staying for 15-17 seconds at 50-52A current? This is not clear to me. I would expect this level of current for short times during the jump but in the graphs it looks like this current stays at this level for several seconds. it looks like the leg joints are loaded by constraints while the leg is pushing down, but i am not sure.

 In the test did you also try for negative current to see if the torque to current ratio as low as with the positive current case?

In the positive current case from 27 to 32 sec the torque to current ratio looks ok (still lower than the hip but not so out) . In the negative current from 33 to 49 though  the torque  to current ratio is half. 

it can be that the rotor slipped in the shaft and the phase angle is not correct anymore.

**Comment by stecorda** [comment]
In my opinion the jpint is too close to the mechanical limit and is pushing against the mechanical stop for several seconds causing the overheating. Is it running in impedance mode right? In any case the current have to be not more than 30A in any case (at least for the hip), I"ve to verify in the fw that this condition is met, I do not understand who's putting the current ref to 50 or more amps.maybe the observer for friction compensation or other in the torque control loop

**Comment by ntsagarakis** [comment]
the mechanical limits can be the constraint,  we need to see the pose of the leg while the knee current was at 50A for several seconds. 
For the current limit I guess it has been changed to higher limit through the configuration file and the 30A limit do not apply, but Andrea can confirm.

**Comment by AndPatr** [comment]
@ntsagarakis, @stecorda 
As for the current, we increased the limits in the configuration file to 55 A. With 30A we were not able to produce decent jumps.
The configuration at which the leg got stuck to -50A in the post-landing one and is visible in the video after 0:24.
@alaurenzi suggested, even if it is something quite rare, that at some point during previous tests or even this one the motor driver teeth slipped a bit and the calibration of the phase angle went off. Which is exactly what @ntsagarakis was saying. To me that look a reasonable explanation. 
So basically, the phase angle of the knee was off, we didn't produce the torque we want and the temperature rose up until a point where the leg shut down (it is however curious that we did not register any error in the ecat_master terminal). By the way, at the beginning we thought to have lost the knee because there was a distinctive smell of burned plastic from that joint, but apparently everything seems to be operational (maybe something melted due to the high temperatures).
I did not try to see if the torque/i_q ratio is symmetric wrt the joint angle, but I can easily test it this morning of later in the afternoon.

**Comment by AndPatr** [comment]
As a side note, yesterday - with the help of @Lurentz - we have removed the old soft sheet in favor of a more absorbent one, which also allows for a slight tip slippage during the jump recovery phase.
I performed once again our cyclic test and, for the first time, I'd say it was successfull.
You can see a video [here](url).
The tips tends to bounce on the new surface, but that is something we can easily fix with Lorenzo.
I did not register any torque_reading_out_of_range and the leg was able to make many successive jumps without stopping.
The jump trajectory I used is always the same, but the resulting jumps are clearly smaller than expected (probably due to the uncalibrated phase angle, but I haven't done any post-processing on the test data yet)

**Comment by stecorda** [comment]
To set the current so high first we need to verify that the board mounted on the joints is the one with 100A sensor current instead of 50A otherwise we can risk to overheat and also damage the current sensors. For the phase angle we can verify it but the joint has to be unmounted and put it on my bench for the verifications (also to verify the current sensor type). Let me know when this could be done.

**Comment by AndPatr** [comment]
@stecorda, @ntsagarakis I am closing this issue since the torque_read_out_of_range problem seems to be resolved.
I will move this to a dedicated issue for the phase angle and the results of the test I performed yesterday

**Comment by AndPatr** [comment]
@stecorda, @ntsagarakis I am closing this issue since the torque_read_out_of_range problem seems to be resolved.
I will move this to a dedicated issue for the phase angle and the results of the test I performed yesterday
