### ISSUE TITLE
Bad torque sensing / tracking

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/awesome_leg#3]
Hi all @ntsagarakis  @lurentz @TheCzar87 @AndPatr @FrancescoRuscelli 
With @DavideAntonucci we have performed some preliminary tests on the *AwesomeLeg* hardware. 

We found the torque tracking/sensing on the knee pitch to be way off, as seen from the following pictures, where the measured torque `*/torque` is compared with the torque reference as generated by the impedance controller `*/torque_imp`, while we manually apply a force to the system.

Note how the hip pitch joint is showing a good tracking performance; on the other hand, the knee joint torque measurement never exceeds 1 Nm, in the face of a required torque that exceeds 15 Nm. Consequently, the required joint impedance is clearly not realized, and therefore model-based torque controllers cannot be employed.

![xbot2_gui_chart__20211220_173750_161](https://user-images.githubusercontent.com/22152172/146802656-d7e8006c-64bc-4927-bf44-a939dd51e80f.png)
![xbot2_gui_chart__20211220_173816_395](https://user-images.githubusercontent.com/22152172/146802665-8bf6a7da-ca50-42e8-a71f-2de400cbe156.png)
 

Could this be due to the high friction that we noticed when moving the knee joint manually?

If there is any other test that you'd like us to perform, please write it down in the comments!

**Comment by ntsagarakis** [comment]
if free, was the knee joint moving in the direction of the reference torque even if the sensing was reporting almost zero torque? Do you have other date to show e.g. motor currents
?

**Comment by alaurenzi** [comment]
Under a moderate impedance of `K = 500, D = 10`, with torque control gains `k_p = 1.0, k_d = 0.003, f_c = 0.9`. The configuration was an L-shaped one with the knee at right angles in order to have some useful lever arm.

**Comment by ntsagarakis** [comment]
ok but then you sent some  reference motion or how the torque references were generated? where these feedforward?

**Comment by ntsagarakis** [comment]
if the second is the case the obviously we have an issue with the torque sensing itself. Can you try to do the same in stiff position mode and monitor the torque measurement and see if we have the same behavior.  in that case we should check the calibration value of the torque sensor in the firmware,  the two joints should have very similar values.  it is all good then we need to inspect the torque sensor. The friction can have an effect but not this, the sensor should be able to report reasonable measurements even with the friction.

**Comment by alaurenzi** [comment]
Reference is constant, an external force is applied. So the torque reference is changing because the joint position (and velocity) is changing.

**Comment by alaurenzi** [comment]
Interestingly, position tracking (under the same impedance gains) is good:
![xbot2_gui_chart__20211220_182126_874](https://user-images.githubusercontent.com/22152172/146807267-4734d025-42bc-4ca8-9048-c5dcb9407797.png)

**Comment by alaurenzi** [comment]
Position mode and vertical load applied manually (L-shape configuration as before).
Given the joint configuration, the two efforts are supposed to be roughly the same..
![xbot2_gui_chart__20211220_183806_960](https://user-images.githubusercontent.com/22152172/146809610-fb56feb5-5b6d-4e02-8972-442d8bd1f09f.png)

**Comment by alaurenzi** [comment]
Motor current from the same setup (L-shape, vertical force, position mode)

![Screenshot from 2021-12-20 18-47-23cropped](https://user-images.githubusercontent.com/22152172/146811050-662722aa-91df-43c4-8782-3917841963b4.png)

Hip pitch is blue, knee pitch is red. I was expecting the two motor currents to be roughly the same. What do you think?

**Comment by ntsagarakis** [comment]
But if the current is like this then the joint is not actually controlled. Can the knee joint keep the position at all in position mode?

**Comment by ntsagarakis** [comment]
if gains in the controllers are set correctly in the firmware this does not make sense unless the electronics are faulty,  the variation in the current measured can be due to the backemf when you backdrive the joint because with this current i believe you should be able to backdrive the joint, is this the case?

**Comment by ntsagarakis** [comment]
I am confused now by looking now the position tracking that looks good. Are the current graphs from the good position tracking experiment that the the joint looks to follow the position reference or from some other experiment? Is the good position tracking achieved under position or impedance control mode?

**Comment by alaurenzi** [comment]
To clarify: position tracking is working well in both position and impedance mode.

Issues are:
 - bad torque reading and/or tracking makes the apparent joint impedance very far from the desired one; it feels very very damped instead
 - very different current absorption for the two motors when loaded similarly (in a static scenario)

Basically all plots are with fixed reference, except the position tracking one.

**Comment by ntsagarakis** [comment]
But how the position tracking works if the current is so low in the motor?  This current level of less than than 1.5-1.7A is not even enough to overcome the friction and move the joint.  

It looks very strange,  with the current and torque close to zero the joint cannot track unless we do not receive the correct readings.  With such a big error in torque the torque controller output should produce a large current reference. if the current is so low  this result in a large current error that will cause saturation of of voltage output produced by the PI current controller. 
Are we sure that the current limit of the actuator is set properly and not to a low value?


The joint is heavily damped by itself due to some issue in the tolerances of the mechanics. did you try with different gains of the torque controller particularly with high friction compensation close to 1? May there is an issue with the collection of the friction data too but this will not explain the almost zero current. 

Another possibility that i can think is that one of the current sensor to be faulty or one of the corresponding phases of the motor with that  sensor to have bad connection with motor driver so the motor is commutated only with 2 phases.

**Comment by alaurenzi** [comment]
Nikos, I just realised that the labels for the y axis of the current plot are cropped by mistake to show the last digit only :D

The current absorption of the knee (red) goes all the way to 10A, the hip to -3A

**Comment by TheCzar87** [comment]
Hi All,

The torque sensor looks operational, because in the first graph, there is a read value and it is consistent as well.
About the current: the two motors cannot be compared in this scenario because the second one has super high friction on link side (as reported during the testing). Also the current to overcome the static friction is 6 times higher rather than hip pitch.

About the current sensor: the sensors are operational, checked and compared with the oscilloscope with an external current probe, to measure the real friction and the KT value.

Another point is that we never tried to control in impedance mode a joint with this friction, therefore, maybe the controller is not working properly because is relying on parameters (for example Geared_motor_inertia) that are in reality totally off.

Bests,
Paolo.
